# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://wiki.openafs.org/HowToBuildOpenAFSFromSource/

Vagrant.configure("2") do |config|
#  config.vm.box = "hashicorp/precise64"
  config.vm.box = "bento/debian-8.4"
  config.vm.hostname = "openafs-debian-dev"
  config.vm.network "private_network", type: "dhcp"
#  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  ["vmware_fusion", "vmware_workstation", "virtualbox"].each do |provider|
    config.vm.provider provider do |v, override|
      host = RbConfig::CONFIG['host_os']
      v.memory = get_memory_setting(host)
      v.cpus = get_cpu_setting(host)
    end
  end

  # config.vm.provision "shell", inline: $shell
  config.vm.provision "shell", path: "provision_script.sh"
  # ssh keys management
  config.vm.provision "shell" do |s|
    ssh_prv_key = ""
    ssh_pub_key = ""
    if File.file?("#{Dir.home}/.ssh/openafs-gerrit")
      ssh_prv_key = File.readlines("#{Dir.home}/.ssh/openafs-gerrit")
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/openafs-gerrit.pub").first.strip
    elsif File.file?("#{Dir.home}/.ssh/id_rsa")
      ssh_prv_key = File.read("#{Dir.home}/.ssh/id_rsa")
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    else
      puts "No SSH key found. You will need to remedy this before pushing to gerrit."
    end
    s.inline = <<-SHELL
      if grep -sq "#{ssh_pub_key}" /home/vagrant/.ssh/authorized_keys; then
        echo "SSH keys already provisioned."
        exit 0;
      fi
      echo "SSH key provisioning."
      mkdir -p /home/vagrant/.ssh/
      touch /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} > /home/vagrant/.ssh/id_rsa.pub
      chmod 644 /home/vagrant/.ssh/id_rsa.pub
      echo "#{ssh_prv_key}" > /home/vagrant/.ssh/id_rsa
      chmod 600 /home/vagrant/.ssh/id_rsa
      chown -R vagrant:vagrant /home/vagrant
      exit 0
    SHELL
  end
end

# Use 1/divider of the available memory
# TODO: use 1/divider or 2 GB, whichever is larger
def get_memory_setting(host)
  divider = 4
  if host =~ /darwin/
    mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / divider
  elsif host =~ /linux/
    mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / divider
  else # Windows
    mem = `for /F "tokens=2 delims==" %i in ('wmic computersystem get TotalPhysicalMemory /value') do @echo %i`.to_i / 1024 / 1024 / divider
  end
  return mem
end

def get_cpu_setting(host)
  if host =~ /darwin/
    cpus = `sysctl -n hw.ncpu`.to_i
  elsif host =~ /linux/
    cpus = `nproc`.to_i
  else # Windows
    cpus = `for /F "tokens=2 delims==" %i in ('wmic cpu get NumberOfCores /value') do @echo %i`.to_i
  end
  return cpus
end
